project_id = "fqcsnlghwugkkwsegpsb"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.send-contact-email]
verify_jwt = false

[functions.submit-puppy-booking]
verify_jwt = false